//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDeclarationSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class expert
    {
        public int ID { get; set; }
        public string xiangmu_id { get; set; }
        public string zZhuanjia_id { get; set; }
        public string xiangmumingc { get; set; }
        public string phone { get; set; }
        public string mima { get; set; }
        public string e_mail { get; set; }
        public string danwei { get; set; }
    }
}
